using SocialMediaApp.ViewModels;

namespace SocialMediaApp.Views;

public partial class HomePage : ContentPage
{
    private readonly HomeViewModel _vm;

    public HomePage(HomeViewModel vm)
    {
        InitializeComponent();
        BindingContext = vm;
        _vm = vm;
    }

    // Do NOT re-declare InitializeComponent() — it is auto-generated by MAUI's XAML compiler

    protected override async void OnAppearing()
    {
        base.OnAppearing();
      
    }
}
